Fix/#23 entity mapping not working correctly
meilisearch/meilisearch-symfony pull request #33
Opened 2020-12-12 11:11 UTC by kermitsxb

Small fix for the bundle to work correctly with last version of meilisearch

2020-12-12 15:14 UTC, emulienfou commented
Thanks @kermitsxb  for the PR.
Can you write some tests please?

2020-12-12 16:38 UTC, kermitsxb commented
@emulienfou I have written a small test that assert that the searchService returns something. I took the index data part from the CommandsTest

2020-12-14 18:08 UTC, curquiza requested changes
Thanks a lot for this PR @kermitsxb!! And thanks for the test addition!

One question to be sure that I understand: does this error appear only when the `hits` array was empty?

2020-12-14 18:08 UTC, curquiza commented on src/Services/MeiliSearchService.php
> +        // Check if the engine return results in "hits" key
```suggestion
        // Check if the engine returns results in "hits" key
```

2020-12-14 18:43 UTC, kermitsxb commented
You're welcome @curquiza, thank you all to provide this amazing bundle.

It looks like the meilisearch-http returns an array with the results of the search having an "hits" key (cf : https://github.com/meilisearch/MeiliSearch/blob/dec0e2545d5878a4b316f3f5549373f091dc8328/meilisearch-http/src/helpers/meilisearch.rs on line 239, the array is built before). This has been added 14 months ago.

The Symfony function I've worked on didn't iterate on that array result but on the returned parent array. In order to keep the function working with people using older version I just set the array we iterate on later with the correct array if the key "hits" exists.

2020-12-16 13:04 UTC, curquiza commented
> In order to keep the function working with people using older version I just set the array we iterate on later with the correct array if the key "hits" exists.

Until MeiliSearch is stable, we don't want to add maintenance for the old version of MeiliSearch in the integration tools code bases. Plus, 14 months ago is a really long time for MeiliSearch, there were no integration plugins and this one didn't even exist.

So, I don't really know where the bug comes from because I really doubt the users in the issue use one of the oldest versions of MeiliSearch -> they would have a LOT of other problems.
Do you know where the bug comes from and why the addition you've made would fix it? 🙂

2020-12-16 17:21 UTC, kermitsxb commented
I don't know where the bug comes from since I've started using the bundle and it wouldn't work properly. The only thing I know is that the result are not passed the good way into the function and the fix I've made make it work.

2020-12-16 18:47 UTC, emulienfou commented
Hi @kermitsxb it's probably a mistake from me and forgot to add unit testing for this part of code and tested it correctly.

So instead of doing:
```php
 if (isset($ids['hits'])) {
            $ids = $ids['hits'];
        }
```

Can you directly update the foreach loop:
```php
foreach ($ids as $objectID)
```

And I think we will need to check before entering in the `foreach` loop if `$ids['hits']` exists otherwise throwing an issue.

2020-12-16 23:15 UTC, kermitsxb commented
@emulienfou that's strange that the issue was not encounter before :thinking: 

I'll correct that tomorrow

2020-12-17 13:20 UTC, curquiza commented
Thanks to both of you guys for your involvement!

2021-01-05 12:53 UTC, curquiza commented
Hello @kermitsxb! Do you have some issue with this PR? Is there something we can do for helping?

2021-01-05 16:32 UTC, tstocker-iris commented
Hello @curquiza ! Excuse me for the delay, I was on holiday and just came back to work yesterday, I'm gonna fixed this issue this week and update the PR ;)

2021-01-05 16:33 UTC, kermitsxb commented
Hello @curquiza ! Excuse me for the delay, I was on holiday and just came back to work yesterday, I'm gonna fixed this issue this week and update the PR ;)

2021-01-11 13:37 UTC, kermitsxb commented
Hi @curquiza @emulienfou, 

I've updated the PR with your recommendations.

2021-01-13 12:41 UTC, curquiza submitted a review, later dismissed
I would rather the typo I have already noticed (https://github.com/meilisearch/meilisearch-symfony/pull/33/files#r542596071) before merging, otherwise, it seems ok 🙂
Is it ok for your @emulienfou?

2021-01-13 13:49 UTC, curquiza approved these changes

2021-01-21 14:18 UTC, curquiza commented
Let's merge it because we don't have any feedback of emulienfou who might be busy 🙂

@emulienfou, you still can require changes of course if you see something wrong.

bors merge

2021-01-21 14:20 UTC, merged